args<-commandArgs()
library("randomForest")
fn1=paste(args[6],".binarytmp",sep="")
fn2=paste(args[6],".spectmp",sep="")
fn3=paste(args[6],".pvtmp",sep="")
progdir="./models/full/"
tissue=""
encoding="binary";
tt<-read.table(fn1,header=TRUE)
fn4=paste(progdir,encoding,"-1",tissue,".Rdata",sep="")
load(fn4)
pv1<-predict(model1,tt[,-1],type="prob")[,2]
rm(model1)
gc()
fn4=paste(progdir,encoding,"-2",tissue,".Rdata",sep="")
load(fn4)
pv2<-predict(model2,tt[,-1],type="prob")[,2]
rm(model2)
gc()
fn4=paste(progdir,encoding,"-3",tissue,".Rdata",sep="")
load(fn4)
pv3<-predict(model3,tt[,-1],type="prob")[,2]
rm(model3)
gc()
fn4=paste(progdir,encoding,"-4",tissue,".Rdata",sep="")
load(fn4)
pv4<-predict(model4,tt[,-1],type="prob")[,2]
rm(model4)
gc()
fn4=paste(progdir,encoding,"-5",tissue,".Rdata",sep="")
load(fn4)
pv5<-predict(model5,tt[,-1],type="prob")[,2]
rm(model5)
gc()
fn4=paste(progdir,encoding,"-6",tissue,".Rdata",sep="")
load(fn4)
pv6<-predict(model6,tt[,-1],type="prob")[,2]
rm(model6)
gc()
fn4=paste(progdir,encoding,"-7",tissue,".Rdata",sep="")
load(fn4)
pv7<-predict(model7,tt[,-1],type="prob")[,2]
rm(model7)
gc()
fn4=paste(progdir,encoding,"-8",tissue,".Rdata",sep="")
load(fn4)
pv8<-predict(model8,tt[,-1],type="prob")[,2]
rm(model8)
gc()
fn4=paste(progdir,encoding,"-9",tissue,".Rdata",sep="")
load(fn4)
pv9<-predict(model9,tt[,-1],type="prob")[,2]
rm(model9)
gc()
fn4=paste(progdir,encoding,"-10",tissue,".Rdata",sep="")
load(fn4)
pv10<-predict(model10,tt[,-1],type="prob")[,2]
rm(model10)
gc()
pvbinary<-(pv1+pv2+pv3+pv4+pv5+pv6+pv7+pv8+pv9+pv10)/10

encoding="spec";
tt<-read.table(fn2,header=TRUE)
fn4=paste(progdir,encoding,"-1",tissue,".Rdata",sep="")
load(fn4)
pv1<-predict(model1,tt[,-1],type="prob")[,2]
rm(model1)
gc()
fn4=paste(progdir,encoding,"-2",tissue,".Rdata",sep="")
load(fn4)
pv2<-predict(model2,tt[,-1],type="prob")[,2]
rm(model2)
gc()
fn4=paste(progdir,encoding,"-3",tissue,".Rdata",sep="")
load(fn4)
pv3<-predict(model3,tt[,-1],type="prob")[,2]
rm(model3)
gc()
fn4=paste(progdir,encoding,"-4",tissue,".Rdata",sep="")
load(fn4)
pv4<-predict(model4,tt[,-1],type="prob")[,2]
rm(model4)
gc()
fn4=paste(progdir,encoding,"-5",tissue,".Rdata",sep="")
load(fn4)
pv5<-predict(model5,tt[,-1],type="prob")[,2]
rm(model5)
gc()
fn4=paste(progdir,encoding,"-6",tissue,".Rdata",sep="")
load(fn4)
pv6<-predict(model6,tt[,-1],type="prob")[,2]
rm(model6)
gc()
fn4=paste(progdir,encoding,"-7",tissue,".Rdata",sep="")
load(fn4)
pv7<-predict(model7,tt[,-1],type="prob")[,2]
rm(model7)
gc()
fn4=paste(progdir,encoding,"-8",tissue,".Rdata",sep="")
load(fn4)
pv8<-predict(model8,tt[,-1],type="prob")[,2]
rm(model8)
gc()
fn4=paste(progdir,encoding,"-9",tissue,".Rdata",sep="")
load(fn4)
pv9<-predict(model9,tt[,-1],type="prob")[,2]
rm(model9)
gc()
fn4=paste(progdir,encoding,"-10",tissue,".Rdata",sep="")
load(fn4)
pv10<-predict(model10,tt[,-1],type="prob")[,2]
rm(model10)
gc()
pvspec<-(pv1+pv2+pv3+pv4+pv5+pv6+pv7+pv8+pv9+pv10)/10

pv=pvbinary*0.6+pvspec*0.4
pvout<-cbind(pvbinary,pvspec,pv,pv)
write.table(pvout,file=fn3)


